<div class="well">
    <h4><i class="glyphicon glyphicon-search"></i> Blog Search...</h4>
    <div class="input-group">
        <input type="text" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
    </div>
    <!-- /input-group -->
</div>