<div class="row">
    <div class="col-md-9">
        <h1 class="page-title">Update your password</h1>
        <div class="page-body">
            <form class="form-horizontal" role="form" method="post" action="<?php echo $this->serverUrl($this->url('company', array('action'=>'changepass'))); ?>">
                <input type="hidden" name="id" value="<?php echo $id; ?>" />
                <div class="form-group">
                    <label for="password" class="col-md-3 control-label">New Password</label>
                    <div class="col-md-5">
                        <input type="password" class="form-control" name="password" value="" placeholder="New Password" autocomplete="off">
                    </div>
                </div>
                <div class="form-group">
                    <label for="confpassword" class="col-md-3 control-label">Confirm Password</label>
                    <div class="col-md-5">
                        <input type="password" class="form-control" name="confpassword" value="" placeholder="Confirm Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-5">
                        <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                            &nbsp Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
