<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1>Change logo</h1>
        </div>
        <div class="page-body">
            <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data" action="<?php echo $this->serverUrl($this->url('company', array('action'=>'changelogo'))); ?>">
                <input type="hidden" name="id" value="<?php echo $id; ?>" />
                <div class="form-group">
                    <label for="password" class="col-md-3 control-label">Upload Logo</label>
                    <div class="col-md-5">
                        <input type="file"  name="logo" value="" placeholder="Upload Logo" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-5">
                        <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                            &nbsp Upload
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
