<script type="text/javascript">
    function getupdatedetailform(){
	jQuery.ajax({
            url: '<?php echo $this->serverUrl($this->url('employer',
                    array('action'=>'ajaxupdatedesc'))); ?>',
            type: 'POST',
            dataType: 'JSON',
            data: {
                'id': <?php echo $company->id; ?>,
                'isAjax': true
            },
            success: function(data, status){
                $('#statedrop').find('option').remove().end().append('<option value="">---- Select state ----</option>').val(' ');
                if(data.status == 'error'){
                    // Perform any operation on error
                    $('#editdesc').show();
                    $('#descriptionshow').html(data.description);
                }else{
                    $('#editdesc').hide();
                    $('#descriptionshow').html(data.description);
                }
            },
            error : function(xhr, textStatus, errorThrown) {
                if (xhr.status === 0 || xhr.status == 404 || xhr.status == 500
                    || errorThrown === 'parsererror' || errorThrown === 'timeout' 
                    || errorThrown === 'abort' ) {
                    console.log('Not connect.\n Verify Network.');
                } else {
                    console.log('There was some error. Try again.');
                }
            },
            complete: function(){
                // Perform any operation need on success/error
            }
	});
    }
    
    function updatedesc(){
	jQuery.ajax({
            url: '<?php echo $this->serverUrl($this->url('employer',
                    array('action'=>'updatedesc'))); ?>',
            type: 'POST',
            dataType: 'JSON',
            data: {
                'id': <?php echo $company->id; ?>,
                'description': document.getElementById('description').value 
            },
            success: function(data, status){
                if(data.status == 'success'){
                    // Perform any operation on error
                    $('#editdesc').show();
                    $('#descriptionshow').html(data.description);
                }
            },
            error : function(xhr, textStatus, errorThrown) {
                if (xhr.status === 0 || xhr.status == 404 || xhr.status == 500
                    || errorThrown === 'parsererror' || errorThrown === 'timeout' 
                    || errorThrown === 'abort' ) {
                    console.log('Not connect.\n Verify Network.');
                } else {
                    console.log('There was some error. Try again.');
                }
            },
            complete: function(){
                // Perform any operation need on success/error
            }
	});
    }
    
    
</script>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-9">
            <div class="span4">
                <blockquote>
                    <p>Welcome <?php echo $company->companyname; ?>!</p>
                    <small><cite title="Source Title"><?php echo $company->state.', '.$company->country; ?>  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                </blockquote>
                <p>
                    <i class="glyphicon glyphicon-envelope"></i> <?php echo $user->email; ?> <br>
                    <i class="glyphicon glyphicon-globe"></i> <?php echo $company->url; ?> <br>
                    <i class="glyphicon glyphicon-time"></i> Since <?php echo $this->dateFormat(new DateTime($user->createdat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM); ?>
                </p>
            </div>
            <div class="row">
                <a id="editdesc" href="javascript:void(0)" onclick="getupdatedetailform();"><i class="glyphicon glyphicon-edit"></i></a>
                <div id="descriptionshow"><?php echo $company->description; ?></div>
            </div>
        </div>
    </div>
</div> 