<div class="row">
    <div class="panel-heading">
        <h1>Editing <b><?php echo $company->company; ?></b></h1>
    </div>
    <div class="panel-body">
        <form id="signupform" class="form-horizontal" role="form"
              action="<?php echo $this->serverUrl($this->url('company', array('action'=>'update'))); ?>" method="post">
            <input type="hidden" name="id" value="<?php echo $company->id; ?>" />            
            <input type="hidden" name="assoc_id" value="<?php echo $company->assoc_id; ?>" />            
            <div class="form-group">
                <label for="conf-password" class="col-md-3 control-label">Company</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="company" placeholder="Company" value="<?php echo $company->company; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="conf-password" class="col-md-3 control-label">Contact Firstname</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="firstname" placeholder="Firstname" value="<?php echo $company->firstname; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="conf-password" class="col-md-3 control-label">Contact Lastname</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="lastname" placeholder="Lastname" value="<?php echo $company->lastname; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="conf-password" class="col-md-3 control-label">Email</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="email" placeholder="Lastname" value="<?php echo $company->email; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="address1" class="col-md-3 control-label">Address Line 1</label>

                <div class="col-md-6">
                    <input type="text" class="form-control" name="address1" placeholder="Address Line 1" value="<?php echo $company->address1 ; ?>" />
                </div>
            </div>
            <div class="form-group">
                <label for="address2" class="col-md-3 control-label">Address Line 2</label>

                <div class="col-md-6">
                    <input type="text" class="form-control" name="address2" placeholder="Address Line 2" value="<?php echo $company->address2 ; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="country" class="col-md-3 control-label">Country</label>

                <div class="col-md-6">
                    <select id="country" class="form-control" onchange="getregion(this) " name="country">
                        <option selected="" value="-1">---- Select country ----</option>
                        <?php foreach($countrys as $val){ ?>
                        <option value="<?php echo $val->iso; ?>" <?php if($company->country == $val->iso){ ?> selected="selected" <?php } ?> ><?php echo $val->nicename; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="state" class="col-md-3 control-label">State</label>
                <div class="col-md-6">
                    <select id="statedrop" class="form-control" name="state">
                        <option value="">---- Select state ----</option>
                    </select>
                    <input id="statetext" type="text" class="form-control" name="statetext" placeholder="State" value=""
                           style="display:none;" />
                </div>
            </div>
            <div class="form-group">
                <label for="city" class="col-md-3 control-label">City</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" name="city" placeholder="City" value="<?php echo $company->city ; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="postcode" class="col-md-3 control-label">Postcode</label>

                <div class="col-md-6">
                    <input type="text" class="form-control" name="postcode" placeholder="Postcode" value="<?php echo $company->postcode ; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="telephone" class="col-md-3 control-label">Phone</label>

                <div class="col-md-6">
                    <input type="text" class="form-control" name="phone" placeholder="Telephone" value="<?php echo $company->phone ; ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="fax" class="col-md-3 control-label">Fax</label>

                <div class="col-md-6">
                    <input type="text" class="form-control" name="fax" placeholder="Fax" value="<?php echo $company->fax ; ?>">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">&nbsp;</label>
                <div class="col-md-6 checkbox">
                    <input id="login-remember" type="checkbox" name="remember" value="1"> I agree to <a href="javascript:void(0);" target="_blank">Terms & Conditions</a>
                </div>
            </div>
            <div class="form-group">
                <!-- Button -->
                <div class="col-md-offset-3 col-md-9">
                    <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i>
                        Update
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    window.onload = function() {
        var obj = document.getElementById('country');
        getregion(obj);
    };
    function getregion(obj){
	jQuery.ajax({
		url: '/ajax/region',
		type: 'POST',
		dataType: 'JSON',
		data: {'country': jQuery('#country').val()},
		success: function(data, status){
                    $('#statedrop').find('option').remove().end().append('<option value="">---- Select state ----</option>').val(' ');
                    if(data.status == 'error'){
                        // Perform any operation on error
                        $('#statetext').css("display","block");
                        $('#statedrop').css("display","none");
                        $('#statetext').val('<?php echo $company->state ?>');
                    }else{
                        $('#statetext').css("display","none");
                        $('#statedrop').css("display","block");
                        // Perform any operation on success);
                        var region = JSON.parse(JSON.stringify(data.region));
                        for(i = 0; i < data.region.length; i++){
                            $('#statedrop').append($('<option>', { 
                                value: region[i].code,
                                text : region[i].title
                            }));
                        }
                        $("#statedrop").children().filter(function() {
                            return $(this).val() == '<?php echo $company->state ?>';
                          }).prop('selected', true);
                    }
		},
		error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connect.\n Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('There was some error. Try again.');
                    }
		},
		complete: function(){
                    // Perform any operation need on success/error
		}
	});
    }
</script>