<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1><?php echo $company->companyname; ?></h1>
        </div>
        <div class="panel-body">
            <div class="col-lg-3">
                <img class="pull-left" src="<?php echo $company->logo; ?>" alt="" title="<?php echo $company->companyname; ?>" />
            </div>
            <?php echo $company->description; ?>
            <?php 
                $address = $company->address1.$company->address2.$company->address3.$company->city.$company->state.$company->country.$company->postcode; 
            ?>    
            <div class="gmap">
                <iframe width="600" height="450"  frameborder="0" style="border:0;margin: 10px 0px;" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDbpzm__Em8dsmDI0_XRCF40VqytZAkmuM&q=<?php echo $address; ?>"></iframe>
            </div>
        </div>
    </div>
</div>

