<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div data-wow-delay="600ms" data-wow-duration="1000ms" class="media contact-info wow fadeInDown animated" style="visibility: visible; animation-duration: 1000ms; animation-delay: 600ms; animation-name: fadeInDown; background: url('<?php echo $this->basePath('front/img/contact.png') ?>') no-repeat scroll 100% 0;">
                <div class="pull-left">
                    <i class="fa fa-phone"></i>
                </div>
                <div class="media-body col-md-7">
                    <h2>Have a question or need a custom quote?</h2>
                    <p>We would like to respond your queries that you may have. You can mail you queries or contact us <a href="mailto:support@goyalhr.com"><i class="fa fa-envelope icon"></i> support@goyalhr.com</a> or <i class="fa fa-phone-square icon"></i> or <i class="fa fa-whatsapp icon"></i>&nbsp;+91 9835 565 108.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <p class="navbar-text pull-left">
                    &copy; 2005 - <?php echo date('Y') ?> by Goyal HR Consultant. <?php echo $this->translate('All rights reserved.') ?>
                </p>
            </div>
            <div class="col-sm-6">
                <?php // <-- Update this !!
                    echo $this->navigation('footer')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('pull-right');
                ?>
            </div>
        </div>
    </div>
</footer>


