<header>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('front/img/logo.png') ?>" alt="Hr Consultancy"/>&nbsp;<?php echo $this->translate('') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <?php // <-- Update this !!
                echo $this->navigation('left')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    // ->setPartial('partial/breadcrumb.phtml')
                    ->setUlClass('nav navbar-nav');
            ?>
            <?php // <-- Update this !!
                echo $this->navigation('right')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    // ->setPartial('partial/breadcrumb.phtml')
                    ->setUlClass('nav navbar-nav pull-right');
            ?>
        </div><!--/.nav-collapse -->
    </div>
</nav>
    </header>