<header>
    <div class="top-bar">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-4">
                    <div class="top-number"><p><i class="fa fa-phone-square"></i> or <i class="fa fa-whatsapp"></i>&nbsp;+91 9835 565 108</p></div>
                </div>
                <div class="col-sm-6 col-xs-8">
                   <div class="social">
                        <ul class="social-share">
                            <li><a href="https://www.facebook.com/Goyal-HR-Consulting-897871160248188" target="_blank"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://twitter.com/GoyalHrConsult" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://plus.google.com/u/0/115960799716399067901" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="https://www.linkedin.com/company/goyal-hr-consulting" target="_blank"><i class="fa fa-linkedin"></i></a></li> 
                            <li><a href="skype:goyalhrconsulting" target="_blank"><i class="fa fa-skype"></i></a></li>
                        </ul>
                        <div class="search">
                            <form role="form">
                                <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                <i class="fa fa-search"></i>
                            </form>
                       </div>
                   </div>
                </div>
            </div>
        </div><!--/.container-->
    </div><!--/.top-bar-->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('front/img/logo.png') ?>" alt="Hr Consultancy"/>&nbsp;<?php echo $this->translate('') ?></a>
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <?php // <-- Update this !!
                    echo $this->navigation('left')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav');
                ?>
                <?php // <-- Update this !!
                    echo $this->navigation('right')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        // ->setPartial('partial/breadcrumb.phtml')
                        ->setUlClass('nav navbar-nav');
                ?>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</header>