<meta charset="utf-8">
        <?php echo $this->headTitle('HR Consultancy '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('front') . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('front') . '/css/style.css')
                        ->prependStylesheet($this->basePath('front') . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath('front') . '/css/bootstrap.min.css') 
						->prependStylesheet($this->basePath('front') . '/css/font-awesome.min.css')
						?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('front') . '/js/bootstrap.min.js')
            ->prependFile($this->basePath('front') . '/js/jquery.min.js')
            ->prependFile($this->basePath('front') . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('front') . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>