<?php
$title = 'Edit <strong>'. $menu->title.'</strong>';
$this->headTitle($title);
?>
<div class="row">
    <h3><?php echo $title; ?></h3>
    <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin-menu', array('action'=>'save'))); ?>">
        <input type="hidden" name="id" value="<?php echo $menu->id; ?>" />
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Title</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $menu->title; ?>" name="title" placeholder="Title">
            </div>
        </div>
		<div class="form-group">
            <label for="label" class="col-md-2 control-label">Label</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $menu->label; ?>" name="label" placeholder="Label">
            </div>
        </div>
		<div class="form-group">
            <label for="route" class="col-md-2 control-label">Route</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $menu->route; ?>" name="route" placeholder="Route">
            </div>
        </div>
        <div class="form-group">
            <label for="route" class="col-md-2 control-label">Parent Menu</label>
            <div class="col-md-5">
                <select class="form-control" name="parent_id">
                    <option selected="" value="-1">---- Choose from option's ----</option>
                    <?php foreach($menus as $val){ ?>
                    <option value="<?php echo $val->id; ?>" <?php if($menu->parent_id == $val->id){ echo 'selected="selected"'; } ?> ><?php echo $val->title; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="sort_order" class="col-md-2 control-label">Sort Order</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $menu->sort_order; ?>" name="sort_order" placeholder="Sort Order">
            </div>
        </div>
        <div class="form-group">
            <label for="route" class="col-md-2 control-label">Status</label>
            <div class="col-md-5">
                <select class="form-control" name="status">
                    <option selected="" value="-1">---- Choose from option's ----</option>
                    <option value="active" <?php if($menu->status == 'active'){ echo 'selected="selected"'; } ?>>Active</option>
                    <option value="inactive" <?php if($menu->status == 'inactive'){ echo 'selected="selected"'; } ?>>In Active</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Update
                </button>
            </div>
        </div>
    </form>
</div>