
<?php
$title = 'Manage Jobs';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->serverUrl($this->url('employer', array('action'=>'jobadd', 'id' => $id)));?>">Post new job</a>
    </p>

    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <th>Id</th>
            <th>Title</th>
            <th>Role</th>
            <th>Type</th>
            <th>Description</th>
            <th>Location</th>
            <th>Status</th>
            <th width="200">Posted On</th>
            <th width="75">&nbsp;</th>
        </tr>
        <?php foreach ($jobs as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $this->escapeHtml($val->id);?></td>
                <td><?php echo $this->escapeHtml($val->title);?></td>
                <td><?php echo $this->escapeHtml($val->roles);?></td>
                <td><?php echo $this->escapeHtml($val->type);?></td>
                <td><?php echo $this->escapeHtml($val->description);?></td>
                <td><?php echo $this->escapeHtml($val->location);?></td>
                <td><?php echo $this->escapeHtml($val->status);?></td>
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->postedat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('employer',
                        array('action'=>'edit', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-edit"></i></a> &nbsp;
                    <a href="<?php echo $this->serverUrl($this->url('employer',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
