<?php
    $title = 'Post Comments';
    $this->headTitle($title);
?>
<div class="row">
    <?php
        if ($this->messages) {
            echo '<ul>';
            foreach ($this->messages as $message) {
                echo '<li>' . $message . '</li>';
            }
            echo '</ul>';
        }
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <th width="75">Id</th>
            <th width="150">Name</th>
            <th width="150">Email</th>
            <th width="150">Title</th>
            <th>Messsage</th>
            <th width="250">Posted On</th>
            <th width="100">&nbsp;</th>
        </tr>
        <?php foreach ($comments as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $this->escapeHtml($val->id);?></td>
                <td><?php echo $this->escapeHtml($val->name);?></td>
                <td><?php echo $this->escapeHtml($val->email);?></td>
                <td><?php echo $this->escapeHtml($val->title);?></td>
                <td><?php echo $this->escapeHtml($val->message);?></td>                
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog-comments',
                        array('action'=>'edit', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-edit"></i></a> &nbsp;
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog-comments',
                        array('action'=>'edit', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-ok"></i></a> &nbsp;
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog-comments',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
