
<?php
$title = 'Blogs Management';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->serverUrl($this->url('admin-blog', array('action'=>'add')));?>">Add new post</a>
    </p>

    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <th>Id</th>
            <th>Title</th>
            <th>URL Path</th>
            <th>Author</th>
            <th>Description</th>
            <th width="200">Created At</th>
            <th width="200">Updated At</th>
            <th width="90">&nbsp;</th>
        </tr>
        <?php foreach ($blogs as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $this->escapeHtml($val->id);?></td>
                <td><?php echo $this->escapeHtml($val->title);?></td>
                <td><?php echo $this->escapeHtml($val->identifier);?></td>
                <td><?php echo $this->escapeHtml($val->author);?></td>
                <td><?php echo $this->escapeHtml($val->description);?></td>
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->updatedat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog-comments',
                        array('action'=>'index', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-comment"></i></a> &nbsp;
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog',
                        array('action'=>'edit', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-edit"></i></a> &nbsp;
                    <a href="<?php echo $this->serverUrl($this->url('admin-blog',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>