<?php
$title = 'New Region';
$this->headTitle($title);
?>
<div class="row">
    <h3>Add new region</h3>
    <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin-region', array('action'=>'save'))); ?>">
        <div class="form-group">
            <label for="country" class="col-md-2 control-label">Country</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $region->country_id; ?>" name="country_id" placeholder="Country">
            </div>
        </div>
		<div class="form-group">
            <label for="code" class="col-md-2 control-label">Code</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $region->code; ?>" name="code" placeholder="Code">
            </div>
        </div>
		<div class="form-group">
            <label for="name" class="col-md-2 control-label">Name</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $region->default_name; ?>" name="default_name" placeholder="Name">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>