<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Admin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('backend') . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('backend') . '/css/style.css')
        ->prependStylesheet($this->basePath('backend') . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath('backend') . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('backend') . '/js/bootstrap.min.js')
        ->prependFile($this->basePath('backend') . '/js/jquery.min.js')
        ->prependFile($this->basePath('backend') . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('backend') . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>

<body style="padding-top: 70px;">

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('admin') ?>"><img src="<?php echo $this->basePath('backend/img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Adminpanel') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo $this->navigation('admin-nav')
                ->menu()
                ->setUlClass('nav navbar-nav')
                ->setMaxDepth(0)
                ->setRenderInvisible(false)?>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
</div> <!-- /container -->
<footer class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <p class="navbar-text pull-left">
            &copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?>
        </p>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
