<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Goyal HR '. $this->translate('Consultaning'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('backend') . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('backend') . '/css/style.css')
                        ->prependStylesheet($this->basePath('backend') . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath('backend') . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('backend') . '/js/bootstrap.min.js')
            ->prependFile($this->basePath('backend') . '/js/jquery.min.js')
            ->prependFile($this->basePath('backend') . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('backend') . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('admin') ?>"><img src="<?php echo $this->basePath('backend/img/logo.png') ?>" alt="HR Consultancy"/>&nbsp;<?php echo $this->translate('') ?></a>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php 
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <ul><li>')
                    ->setMessageSeparatorString('</li><li>')
                    ->setMessageCloseString('</li></ul></div>');

                echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
                <p class="navbar-text pull-left">
                    &copy; 2005 - <?php echo date('Y') ?> by Goyal HR Consultant. <?php echo $this->translate('All rights reserved.') ?>
                </p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
