<?php
$title = 'New Banner';
$this->headTitle($title);
?>
<div class="row">
    <h3>Adding new banner</h3>
    <form class="form-horizontal" role="form" id="tab" method="post" enctype="multipart/form-data" action="<?php echo $this->serverUrl($this->url('admin-banner', array('action'=>'save'))); ?>">
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Title</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $banner->title; ?>" name="title" placeholder="Title">
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Banner</label>
            <div class="col-md-5">
                <input type="file"  value="<?php echo $banner->banner; ?>" name="banner" placeholder="Banner">
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">URL Link</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $banner->urlpath; ?>" name="urlpath" placeholder="URL Link">
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Sort Order</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $banner->sortorder; ?>" name="sortorder" placeholder="Sort Order">
            </div>
        </div>
        <div class="form-group">
            <label for="content" class="col-md-2 control-label">Status</label>
            <div class="col-md-7">
                <select name="status" class="form-control">
                    <option value="1">Active</option>
                    <option value="2">Inactive</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>