
<?php
$title = 'Manage Skills';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div id="linkaddskills">
        <a href="javascript:void(0)" onclick="displayaddskill();">Add new skills</a>
    </div>
    <div class="col-md-9" id="addskils" style="display: none;">
        <form id="skillsform" class="form-horizontal" role="form"
                  action="<?php echo $this->serverUrl($this->url('jobseeker', array('action'=>'skills'))); ?>" method="post">
            <input type="hidden" name="id" value="<?php echo $id; ?>" />            
            <fieldset><legend>Add you skills</legend>
                <table id="skills-add">
                    <tr>
                        <td>Skill</td>
                        <td>Exp. in Year</td>
                        <td>Exp. in Month</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="skills[1][title]" placeholder="Title" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="skills[1][exp_in_year]" placeholder="Exp. in year" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="skills[1][exp_in_month]" placeholder="Exp. in month" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <a href="javascript:void(0);" onclick="addmore()">+&nbsp;Add more skill</a>
                <input type="hidden" id="skillcnt" value="2" name="skillcnt" />
                <div class="form-group">
                    <div class="col-md-9">
                        <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                            Submit
                        </button> or 
                        <button id="btn-signup" type="button" class="btn btn-primary" onclick="hideaddskill()"><i class="icon-hand-right"></i>
                            Cancel
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <td>&nbsp;</td>
            <th>Title</th>
            <th>Exp. in Year</th>
            <th>Exp. in Month</th>
            <th width="75">&nbsp;</th>
        </tr>
        <?php foreach ($skills as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td>&nbsp;</td>
                <td><?php echo $this->escapeHtml(ucwords($val->title));?></td>
                <td><?php echo $this->escapeHtml($val->exp_in_year);?></td>
                <td><?php echo $this->escapeHtml($val->exp_in_month);?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('admin-region',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<script type="text/javascript">
    function displayaddskill(){
        document.getElementById('addskils').style.display = 'block';
        document.getElementById('linkaddskills').style.display = 'none';
    }
    function hideaddskill(){
        document.getElementById('addskils').style.display = 'none';
        document.getElementById('linkaddskills').style.display = 'block';
    }
    function addmore(){
        var i = $('#skillcnt').val();
        var html = "<tr>";
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="skills['+i+'][title]" placeholder="Title" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '            </td>';
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="skills['+i+'][exp_in_year]" placeholder="Exp. in year" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '            </td>';
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="skills['+i+'][exp_in_month]" placeholder="Exp. in month" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '</td>';
            html += "</tr>";
        $('#skills-add').append(html);
        i++;
        $('#skillcnt').val(i);
    }
    
</script>
