<div class="row">
    <div class="col-md-12">
        <h1>Blog Posts</h1>
        <?php foreach ($blogs as $val) : ?>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading"><?php echo $val->title; ?></h4>
                    <p><?php echo $val->description; ?>... <a href="<?php echo $this->serverUrl($this->url('blog',
                            array('action'=>'view', 'id' => $val->id)));?>">Read more</a></p>
                    <ul class="list-inline list-unstyled">
                        <li><span><i class="glyphicon glyphicon-user"></i> by <a href="#"><?php echo $val->author; ?></a></span></li>
                        <li>|</li>
                        <li><span><i class="glyphicon glyphicon-calendar"></i> <?php echo $this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::LONG); ?> </span></li>
                        <li>|</li>
                        <span><i class="glyphicon glyphicon-comment"></i> 2 comments</span>
                        <li>|</li>
                        <li>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                        </li>
                        <li>|</li>
                        <li>
                            <span><i class="fa fa-facebook"></i></span>
                            <span><i class="fa fa-twitter"></i></span>
                            <span><i class="fa fa-google-plus"></i></span>
                        </li>
                    </ul>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>