<style type="text/css">
    body
    {
        padding-top: 20px;
    }
    #myCarousel .nav a small
    {
        display: block;
    }
    #myCarousel .nav
    {
        background: #eee;
    }
    .nav-justified > li > a
    {
        border-radius: 0px;
    }
    .nav-pills>li[data-slide-to="0"].active a { background-color: #16a085; }
    .nav-pills>li[data-slide-to="1"].active a { background-color: #e67e22; }
    .nav-pills>li[data-slide-to="2"].active a { background-color: #2980b9; }
    .nav-pills>li[data-slide-to="3"].active a { background-color: #8e44ad; }
</style>
<script type="text/javascript">
    $(document).ready( function() {
        $('#myCarousel').carousel({
            interval:   4000
        });

        var clickEvent = false;
        $('#myCarousel').on('click', '.nav a', function() {
            clickEvent = true;
            $('.nav li').removeClass('active');
            $(this).parent().addClass('active');
        }).on('slid.bs.carousel', function(e) {
            if(!clickEvent) {
                var count = $('.nav').children().length -1;
                var current = $('.nav li.active');
                current.removeClass('active').next().addClass('active');
                var id = parseInt(current.data('slide-to'));
                if(count == id) {
                    $('.nav li').first().addClass('active');
                }
            }
            clickEvent = false;
        });
    });
</script>


<!-- Start Carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="<?php echo $this->basePath('front/img/About Us.png') ?>">
            <div class="carousel-caption">
                <h3>
                    Headline</h3>
                <p>
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                    ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
        <!-- End Item -->
        <div class="item">
            <img src="<?php echo $this->basePath('front/img/Projects.png') ?>">
            <div class="carousel-caption">
                <h3>
                    Headline</h3>
                <p>
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                    ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
        <!-- End Item -->
        <div class="item">
            <img src="<?php echo $this->basePath('front/img/Portfolio.png') ?>">
            <div class="carousel-caption">
                <h3>
                    Headline</h3>
                <p>
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                    ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
        <!-- End Item -->
        <div class="item">
            <img src="<?php echo $this->basePath('front/img/Services.png') ?>">
            <div class="carousel-caption">
                <h3>
                    Headline</h3>
                <p>
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                    tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                    ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
        <!-- End Item -->
    </div>
    <!-- End Carousel Inner -->
    <ul class="nav nav-pills nav-justified">
        <li data-target="#myCarousel" data-slide-to="0" class="active"><a href="#">About<small>Lorem
                    ipsum dolor sit</small></a></li>
        <li data-target="#myCarousel" data-slide-to="1"><a href="#">Projects<small>Lorem ipsum
                    dolor sit</small></a></li>
        <li data-target="#myCarousel" data-slide-to="2"><a href="#">Portfolio<small>Lorem ipsum
                    dolor sit</small></a></li>
        <li data-target="#myCarousel" data-slide-to="3"><a href="#">Services<small>Lorem ipsum
                    dolor sit</small></a></li>
    </ul>
</div>
<!-- End Carousel -->

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Recruitment Solutions') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Site is under active development. If you are interested in following the development, there is a special portal on the official website which provides links, and much more. This is a great resource for staying up to date with the latest developments!') ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Staffing Solutions') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('The community is working on developing a community site to serve as a repository and gallery for modules. The site is currently live and currently contains a list of some of the modules already available.') ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('Explore Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Outsourcing Solution') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with, you may reach us via mail roshanbhgt@gmail.com. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the mail id roshanbhgt@gmail.com.')) ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('Mail Me') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
