<?php
$title = 'Create new user';
$this->headTitle($title);
?>
<div class="row">
    <?php
    if ($this->messages) {
        echo '<ul>';
        foreach ($this->messages as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</ul>';
    }
    ?>
    <h3>Creating new user</h3>
    <form id="signupform" class="form-horizontal" role="form"
          action="<?php echo $this->serverUrl($this->url('create')); ?>" method="post">
        <div class="form-group">
            <label for="firstname" class="col-md-3 control-label">First Name</label>

            <div class="col-md-6">
                <input type="text" class="form-control" name="firstname" placeholder="First Name">
            </div>
        </div>
        <div class="form-group">
            <label for="lastname" class="col-md-3 control-label">Last Name</label>

            <div class="col-md-6">
                <input type="text" class="form-control" name="lastname" placeholder="Last Name">
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-md-3 control-label">Email</label>

            <div class="col-md-6">
                <input type="text" class="form-control" name="email" placeholder="Email Address">
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-md-3 control-label">Password</label>

            <div class="col-md-6">
                <input type="password" class="form-control" name="passwd" placeholder="Password">
            </div>
        </div>

        <div class="form-group">
            <label for="state" class="col-md-3 control-label">State</label>

            <div class="col-md-6">
                <input type="text" class="form-control" name="state" placeholder="State">
            </div>
        </div>

        <div class="form-group">
            <label for="country" class="col-md-3 control-label">Country</label>

            <div class="col-md-6">
                <input type="text" class="form-control" name="country" placeholder="Country">
            </div>
        </div>

        <?php // echo $captcha->getService()->getHtml();?>

        <div class="form-group">
            <!-- Button -->
            <div class="col-md-offset-3 col-md-9">
                <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i>
                    Submit
                </button>
            </div>
        </div>

    </form>
                
</div>