
<?php
$title = 'Job Applications';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <td style="width:10%;">&nbsp;</td>
            <th>Job Title</th>
			<th>First Name</th>
            <th style="width:25%;">Apply Date</th>
            <th style="width:10%;"></th>
        </tr>
        <?php $i=1; foreach ($jobapplication as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $i++; ?></td>
                <td><?php echo $this->escapeHtml(ucwords($val->jobtitle));?></td>
                <td>
                    <?php 
                        foreach($jobseekers as $jobseeker ){ 
                            if($jobseeker->userid == $val->userid){
                    ?>
                <?php echo $this->escapeHtml(ucwords($jobseeker->firstname.' '.$jobseeker->middlename.' '.$jobseeker->lastname));?>
                <?php }else{ ?>

                <?php  }
                        } 
                ?>
                </td>
                <td>
                    <?php 
                        // echo $this->dateFormat(new DateTime($val->applydate), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM); 
                        echo date("F j, Y, g:i a", strtotime($val->applydate));
                    ?>
                </td>
                <td>
					<a href="<?php echo $this->serverUrl($this->url('admin-jobs',
                        array('action'=>'viewapplication', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-info-sign"></i></a>
                    <a href="<?php echo $this->serverUrl($this->url('admin-jobs',
                        array('action'=>'deleteapplication', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
