<?php 
    use Zend\Session\Container;
    
    // Store data in session
    $user = new Container('user');
?>
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1><?php echo $job->title; ?></h1>
        </div>
        <div class="page-body">
            <p><strong>Position</strong>:- <?php echo $job->position; ?></p>
            <p><strong>Skills Required</strong>:- <?php echo $job->skills; ?></p>
            <p><strong>Roles & Responsibility</strong>:- <?php echo $job->roles; ?></p>
            <p><strong>No of vacancy's</strong>:- <?php echo $job->vacancy; ?></p>
            <p><strong>Job Location</strong>:- <?php echo $job->location; ?></p>
            <p><strong>Salary</strong>:- <?php echo $job->salary; ?></p>
            <p><?php echo $job->description; ?></p>
        </div>
        <?php if($user->id && $user->type == 'jobseeker'){ ?>
        <div>
            <form id="signupform" class="form-horizontal" role="form"
              action="<?php echo $this->serverUrl($this->url('job', array('action'=>'apply'))); ?>" method="post">
                  <div class="form-group">
                    <!-- Button -->
                    <div class="col-md-9">
                        <input type="hidden" name="jobtitle" value="<?php echo $job->title; ?>" />
                        <input type="hidden" name="jobid" value="<?php echo $job->id; ?>" />
                        <input type="hidden" name="userid" value="<?php echo $user->id; ?>" />
                        <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                            Apply Now
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <?php } ?>
    </div>
</div>
