<div class="row">
    <div class="col-md-12">
        <div class="col-md-9">
            <div class="page-header">
                <h1>Welcome <?php echo $employee->firstname.' '.$employee->lastname; ?>!</h1>
            </div>
            <div class="page-body">
                <i class="glyphicon glyphicon-envelope"></i> <?php echo $employee->email; ?> <br>
                <i class="glyphicon glyphicon-time"></i> Since <?php echo $this->dateFormat(new DateTime($employee->createdat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM); ?>
            </div>
        </div>
    </div>
</div> 