
<?php
$title = 'Manage Education';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div id="linkaddeducation">
        <a href="javascript:void(0)" onclick="displayaddeducation();">Add education</a>
    </div>
    <div class="col-md-9" id="addeducation" style="display: none;">
        <form id="skillsform" class="form-horizontal" role="form"
                  action="<?php echo $this->serverUrl($this->url('jobseeker', array('action'=>'education'))); ?>" method="post">
            <input type="hidden" name="id" value="<?php echo $id; ?>" />            
            <input type="hidden" name="userid" value="<?php echo $id; ?>" />            
            <fieldset><legend>Add you education</legend>
                <table id="education-add">
                    <tr>
                        <td>Education</td>
                        <td>Duration in Year</td>
                        <td>Year of Passing</td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="education[1][education]" placeholder="Education" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="education[1][duration_in_year]" placeholder="Duration in year" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="education[1][year_of_passing]" placeholder="Year of Passing" value="" style="width:150px">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <a href="javascript:void(0);" onclick="addmore()">+&nbsp;Add more education</a>
                <input type="hidden" id="educationcnt" value="2" name="educationcnt" />
                <div class="form-group">
                    <div class="col-md-9">
                        <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                            Submit
                        </button> or 
                        <button id="btn-signup" type="button" class="btn btn-primary" onclick="hideaddeducation()"><i class="icon-hand-right"></i>
                            Cancel
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <td>&nbsp;</td>
            <th>Education</th>
            <th>Duration in Year</th>
            <th>Year of Passing</th>
            <th width="75">&nbsp;</th>
        </tr>
        <?php foreach ($educations as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td>&nbsp;</td>
                <td><?php echo $this->escapeHtml(ucwords($val->education));?></td>
                <td><?php echo $this->escapeHtml($val->duration_in_year);?></td>
                <td><?php echo $this->escapeHtml($val->year_of_passing);?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('admin-region',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<script type="text/javascript">
    function displayaddeducation(){
        document.getElementById('addeducation').style.display = 'block';
        document.getElementById('linkaddeducation').style.display = 'none';
    }
    function hideaddeducation(){
        document.getElementById('addeducation').style.display = 'none';
        document.getElementById('linkaddeducation').style.display = 'block';
    }
    function addmore(){
        var i = $('#educationcnt').val();
        var html = "<tr>";
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="education['+i+'][education]" placeholder="Education" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '            </td>';
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="education['+i+'][duration_in_year]" placeholder="Duration in year" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '            </td>';
            html += '            <td>';
            html += '                <div class="form-group">';
            html += '                    <div class="col-md-3">';
            html += '                        <input type="text" class="form-control" name="education['+i+'][year_of_passing]" placeholder="Year of Passing" value="" style="width:150px">';
            html += '                    </div>';
            html += '                </div>';
            html += '</td>';
            html += "</tr>";
        $('#education-add').append(html);
        i++;
        $('#educationcnt').val(i);
    }
    
</script>
