
<?php
$title = 'My Payslips';
$this->headTitle($title);
?>
<div class="row">
    <div class="page-header">  
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="page-body">
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <th>Id</th>
            <th>Employee Code</th>
            <th>Month-Year</th>
            <th width="200">Created At</th>
            <th width="75">&nbsp;</th>
        </tr>
        <?php foreach ($payslips as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $this->escapeHtml($val->employee_id);?></td>
                <td>
                <?php 
                    foreach($associate as $value){ 
                        if($val->employee_id == $value->id){
                            echo $this->escapeHtml($value->username);
                        }
                    }
                ?>
                </td>
                <td>Payslips for <?php echo date("M-Y",  strtotime($val->createdat));?></td>
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('employee',
                        array('action'=>'payslipsdownload', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-download-alt"></i></a> &nbsp;
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
</div>
