<div class="row">
    <?php
    if ($this->messages) {
        echo '<ul>';
        foreach ($this->messages as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</ul>';
    }
    ?>
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-lg-12">
        <div id="signupbox" class="mainbox col-lg-10">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Register as an Company</div>
                </div>
                <div class="panel-body">
                    <form id="signupform" class="form-horizontal" role="form"
                          action="<?php echo $this->serverUrl($this->url('create')); ?>" method="post">

                        <div id="signupalert" style="display:none" class="alert alert-danger">
                            <p>Error:</p>
                            <span></span>
                        </div>
                        <input type="hidden" name="type" value="employer" />
                        <div class="form-group">
                            <label for="firstname" class="col-md-3 control-label">First Name</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="firstname" placeholder="First Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="lastname" class="col-md-3 control-label">Last Name</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="lastname" placeholder="Last Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-3 control-label">Email</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="email" placeholder="Email Address">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password" class="col-md-3 control-label">Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="conf-password" class="col-md-3 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="conf-password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="conf-password" class="col-md-3 control-label">Company Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="companyname" placeholder="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="companytype" class="col-md-3 control-label">Company Type</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="companytype" placeholder="Company Type">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="industrytpe" class="col-md-3 control-label">Industry Type</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="email" placeholder="Email Address">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address1" class="col-md-3 control-label">Address Line 1</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="address1" placeholder="Address Line 1">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address2" class="col-md-3 control-label">Address Line 2</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="address2" placeholder="Address Line 2">
                            </div>
                        </div><div class="form-group">
                            <label for="address3" class="col-md-3 control-label">Address Line 3</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="address3" placeholder="Address Line 3">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="country" class="col-md-3 control-label">Country</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="country" placeholder="Country">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="state" class="col-md-3 control-label">State</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="state" placeholder="State">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="city" class="col-md-3 control-label">City</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="city" placeholder="City">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="postcode" class="col-md-3 control-label">Postcode</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="postcode" placeholder="Postcode">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="telephone" class="col-md-3 control-label">Contact Number</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="telephone" placeholder="Telephone">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="fax" class="col-md-3 control-label">Fax</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="fax" placeholder="Fax">
                            </div>
                        </div>
                        <?php // echo $captcha->getService()->getHtml();?>

                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i>
                                    Sign Up
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>