<div class="row">
    <?php if ($this->messages) { ?>
        <div  id="login-alert" class="alert alert-danger col-sm-12">
            <?php
            echo '<ul>';
            foreach ($this->messages as $message) {
                echo '<li>' . $message . '</li>';
            }
            echo '</ul>';
            ?>
        </div>
    <?php } ?>
    <div id="loginbox" class="mainbox col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">New Users</div>
            </div>

            <div style="padding-top:30px" class="panel-body">
                <p>By creating an account with us, you will be able to comment's on blogs, save the blogs for future reference etc...</p>
                <div class="col-sm-12 controls">
                    <a id="btn-account" href="<?php echo $this->serverUrl($this->url('registercompany')); ?>" class="btn btn-info">Employer Account</a>
					<span style="margin:0 8px;">or</span>
                    <a id="btn-account" href="<?php echo $this->serverUrl($this->url('registerjobseeker')); ?>" class="btn btn-info">Jobseeker Account</a>
                </div>
            </div>
        </div>
    </div>
    <div id="loginbox" class="mainbox col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Registered Users</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a
                        href="<?php echo $this->serverUrl($this->url('forgetpass')); ?>">Forgot password?</a></div>
            </div>

            <div style="padding-top:30px" class="panel-body">
                
                <p>If you have an account with us, please log in.</p>
                
                <form id="loginform" class="form-horizontal" role="form"
                      action="<?php echo $this->serverUrl($this->url('authenticate')); ?>" method="post">

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="email" value=""
                               placeholder="username or email">
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password"
                               placeholder="password">
                    </div>

                    <div class="input-group">
                        <div class="checkbox">
                            <label>
                                <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                            </label>
                        </div>
                    </div>


                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->

                        <div class="col-sm-12 controls">
                            <button id="btn-login" type="submit" class="btn btn-info">
								<i class="icon-hand-right"></i>Login
                            </button>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                Don't have an account!
                                <a href="<?php echo $this->serverUrl($this->url('register')); ?>">Sign Up Here</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>