<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->render('partial/head.phtml'); ?>
    </head>
    <body>
        <?php echo $this->render('partial/header.phtml'); ?>
        <div class="container">
            <?php // echo $this->navigation('left')->breadcrumbs()->setMinDepth(0); // <-- Add this!! ?>
            <?php echo $this->content;?>
        </div> <!-- /container -->
	<?php echo $this->render('partial/footer.phtml'); ?>	
        <?php echo $this->inlineScript() ?>
    </body>
</html>
