<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->render('partial/head.phtml'); ?>
    </head>
    <body>
    <?php echo $this->render('partial/header.phtml'); ?>
    <div class="container">
        <div class='col-md-9 main'>
            <?php echo $this->content; ?>
        </div>
        <div class='col-sm-3 sidebar'>
            <?php echo $this->sidebar; ?>
        </div>
    </div> <!-- /container -->
    <?php echo $this->render('partial/footer.phtml'); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
