<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('front') . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('front') . '/css/style.css')
                        ->prependStylesheet($this->basePath('front') . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath('front') . '/css/bootstrap.min.css') 
						->prependStylesheet($this->basePath('front') . '/css/font-awesome.css')
						?> 

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('front') . '/js/bootstrap.min.js')
            ->prependFile($this->basePath('front') . '/js/jquery.min.js')
            ->prependFile($this->basePath('front') . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('front') . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('front/img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('') ?></a>
            </div>
            <div class="collapse navbar-collapse">
                <?php // <-- Update this !!
                echo $this->navigation('left')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    // ->setPartial('partial/breadcrumb.phtml')
                    ->setUlClass('nav navbar-nav');
                ?>
                <?php // <-- Update this !!
                echo $this->navigation('right')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    // ->setPartial('partial/breadcrumb.phtml')
                    ->setUlClass('nav navbar-nav pull-right');
                ?>
                <!-- <ul class="nav navbar-nav pull-right">
                        <li><a href="<?php // echo $this->serverUrl($this->url('create'));?>">Register</a></li>
                        <li><a href="<?php // echo $this->serverUrl($this->url('create'));?>">Register</a></li>
                        <li class="divider-vertical"></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Log In <strong class="caret"></strong></a>
                            <div class="dropdown-menu" style="padding: 15px;">
                                <form action="<?php // echo $this->serverUrl($this->url('authenticate'));?>" method="post">
                                    Username:<br />
                                    <input type="text" name="username" value="" />
                                    <br /><br />
                                    Password:<br />
                                    <input type="password" name="password" value="" />
                                    <br /><br />
                                    <input type="submit" class="btn btn-info" value="Login" />
                                    <div style="float: right;font-size: 80%;left: 5px;position: relative;top: -25px;"><a href="<?php echo $this->serverUrl($this->url('forgetpass'));?>">Forgot password?</a></div>
                                </form>
                            </div>
                        </li>
                    </ul> -->
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class='col-md-9 main'>
            <?php echo $this->content; ?>
        </div>
        <div class='col-sm-3 sidebar'>
            <?php echo $this->sidebar; ?>
        </div>
    </div> <!-- /container -->
    <footer class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <p class="navbar-text pull-left">
                &copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?>
            </p>
        </div>
    </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
