<?php
$title = 'Edit <strong>'. $page->title.'</strong>';
$this->headTitle($title);
?>
<div class="row">
    <h3><?php echo $title; ?></h3>
    <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin-page', array('action'=>'save'))); ?>">
        <input type="hidden" name="id" value="<?php echo $page->id; ?>" />
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Title</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $page->title; ?>" name="title" placeholder="Title">
            </div>
        </div>
        <div class="form-group">
            <label for="content" class="col-md-2 control-label">Contents</label>
            <div class="col-md-7">
                <textarea name="contents" class="form-control" placeholder="Contents"><?php echo $page->contents; ?></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Update
                </button>
            </div>
        </div>
    </form>
</div>