<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h3><?php echo $job->title; ?></h3>
        </div>
        <div class="page-body">
            <p><?php echo $job->description; ?></p>
            <p><strong>Position</strong>:- <?php echo $job->position; ?></p>
            <p><strong>Skills Required</strong>:- <?php echo $job->skills; ?></p>
            <p><strong>Roles & Responsibility</strong>:- <?php echo $job->roles; ?></p>
            <p><strong>No of vacancy's</strong>:- <?php echo $job->vacancy; ?></p>
            <p><strong>Job Location</strong>:- <?php echo $job->location; ?></p>
            <p><strong>Salary</strong>:- <?php echo $job->salary; ?></p>
        </div>
    </div>
</div>
