
<?php
$title = 'My Dashboard';
$this->headTitle($title);
?>
<div class="row">
    <?php
        if ($this->messages) {
            echo '<div  id="login-alert" class="alert alert-danger col-sm-12">';
                echo '<ul>';
                foreach ($this->messages as $message) {
                    echo '<li>' . $message . '</li>';
                }
                echo '</ul>';
            echo '</div>';
        }
    ?>
    <div class="row">
    <div class="col-md-12">
        <div class="col-md-2">
            <div class="span2">
                <img id="profile-img" src="<?php echo $this->basePath('backend/img/nouser.png'); ?>"  alt="" class="img-thumbnail media-object">
                <i class="glyphicon glyphicon-picture"></i> <a href="javascript:void(0)" onclick="$('#profile-pic').show()">Change profile pic...</a>
                <div id="profile-pic" style="display:none;">
                    <form enctype="multipart/form-data" method="POST" id="my-form-profile">
                        <input name="uploadedfile" type="file"/>
                        <input type="submit" value="Upload" class="btn btn-primary" />&nbsp;<a href="javascript:void(0)" onclick="$('#profile-pic').hide()">Cancel</a>
                    </form>
                    <script type="text/javascript">
                        $('#my-form-profile')
                            .submit( function( e ) {
                                $.ajax( {
                                    url: '<?php echo $this->serverUrl($this->url('admin', array('action'=>'uploadpic'))); ?>',
                                    type: 'POST',
                                    data: new FormData(this ),
                                    processData: false,
                                    contentType: false,
                                    success: function (data) {
                                        var data = JSON.parse(data);
                                        if(data.success){
                                            document.getElementById("profile-img").src= data.file;
                                            document.getElementById("my-form-profile").reset();
                                            $('#profile-pic').hide();
                                        }
                                        return false;
                                    }
                                } );
                                e.preventDefault();
                            } );
                    </script>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div class="span4">
                <blockquote>
                    <p>Welcome <?php echo $admin->firstname; ?>!</p>
                    <small><cite title="Source Title"><?php echo $admin->state.', '.$admin->country; ?>  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                </blockquote>
                <p>
                    <i class="glyphicon glyphicon-envelope"></i> <?php echo $admin->username; ?> <br>
                    <i class="glyphicon glyphicon-log-in"></i> Online <?php echo $this->dateFormat(new DateTime($admin->lastloginat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM); ?> <br>
                    <i class="glyphicon glyphicon-time"></i> Since <?php echo $this->dateFormat(new DateTime($admin->createdat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM); ?>
                </p>
            </div>
            <ul class="nav nav-tabs">
                <li class="active"><a href="#home" data-toggle="tab">Profile</a></li>
                <li><a href="#profile" data-toggle="tab">Password</a></li>
                <li><a href="#list" data-toggle="tab">List</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane active in" id="home">
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin',array('action'=>'update'))); ?>">
                            <input type="hidden" name="id" value="<?php echo $admin->id; ?>" />
                            <div class="form-group">
                                <label for="firstname" class="col-md-2 control-label">First Name</label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" value="<?php echo $admin->firstname; ?>" name="firstname" placeholder="First Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="lastname" class="col-md-2 control-label">Last Name</label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" value="<?php echo $admin->lastname; ?>" name="lastname" placeholder="Last Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-2 control-label">Email</label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" value="<?php echo $admin->username; ?>" name="username" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="state" class="col-md-2 control-label">State</label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" value="<?php echo $admin->state; ?>" name="state" placeholder="State">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="country" class="col-md-2 control-label">Country</label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" name="country" value="<?php echo $admin->country; ?>" placeholder="Country">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-5">
                                    <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tab-pane fade" id="profile">
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" id="tab2" method="post" action="<?php echo $this->serverUrl($this->url('admin',array('action'=>'update'))); ?>">
                            <input type="hidden" name="id" value="<?php echo $admin->id; ?>" />
                            <div class="form-group">
                                <label for="password" class="col-md-2 control-label">New Password</label>
                                <div class="col-md-5">
                                    <input type="password" class="form-control" name="password" value="" placeholder="New Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-5">
                                    <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tab-pane fade" id="list">
                    <div class="panel-body">
                        <p><a href="<?php echo $this->serverUrl($this->url('admin', array('action'=>'add')));?>">Add new user</a></p>
                        <table class="table">
                            <tr style="background-color:#2a6496;color: #ffffff">
                                <th>Id</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Username</th>
                                <th>Created At</th>
                                <th>Last Login At</th>
                                <th>&nbsp;</th>
                            </tr>
                            <?php foreach ($lists as $val) : ?>
                                <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                                    <td><?php echo $this->escapeHtml($val->id);?></td>
                                    <td><?php echo $this->escapeHtml($val->firstname);?></td>
                                    <td><?php echo $this->escapeHtml($val->lastname);?></td>
                                    <td><?php echo $this->escapeHtml($val->username);?></td>
                                    <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM));?></td>
                                    <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->lastloginat), IntlDateFormatter::LONG,IntlDateFormatter::MEDIUM));?></td>
                                    <td>
                                        <a href="<?php echo $this->serverUrl($this->url('admin',
                                            array( 'action'=>'edit', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-edit"></i></a> &nbsp;
                                        <a href="<?php echo $this->serverUrl($this->url('admin',
                                            array( 'action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
