<?php
$title = 'New Block';
$this->headTitle($title);
?>
<div class="row">
    <h3>Creating new block</h3>
    <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin-block', array('action'=>'save'))); ?>">
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Identifier</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $block->identifier; ?>" name="identifier" placeholder="Identifier">
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">Title</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $block->title; ?>" name="title" placeholder="Title">
            </div>
        </div>
        <div class="form-group">
            <label for="content" class="col-md-2 control-label">Content</label>
            <div class="col-md-7">
                <textarea name="content" class="form-control" placeholder="Contents"><?php echo $block->content; ?></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Create
                </button>
            </div>
        </div>
    </form>
</div>