<?php 
    use Zend\Session\Container;

    // Store data in session
    $company = new Container('user');
?>
<div class="profile-sidebar">
<!-- SIDEBAR USERPIC -->
<div class="profile-userpic">
    <img src="<?php echo $company->companylogo; ?>" class="img-responsive" alt="">
</div>
<!-- END SIDEBAR USERPIC -->
<!-- SIDEBAR USER TITLE -->
<div class="profile-usertitle">
    <div class="profile-usertitle-name">
        <?php echo $company->companytitle; ?>
    </div>
    <div class="profile-usertitle-job">
        <?php echo $company->companytype; ?>
    </div>
</div>
<!-- END SIDEBAR USER TITLE -->
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
    <ul class="nav">
        <li class="active">
            <a href="<?php echo $this->serverUrl($this->url('employer')); ?>">
            <i class="glyphicon glyphicon-home"></i>
            Overview </a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employer', array('action'=>'changelogo', 'id' => $company->id))); ?>">
            <i class="glyphicon glyphicon-picture"></i>
            Change Logo</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employer', array('action'=>'edit', 'id' => $company->id))); ?>">
            <i class="glyphicon glyphicon-user"></i>
            Account Information</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employer', array('action'=>'changepass', 'id' => $company->userid))); ?>">
            <i class="glyphicon glyphicon-lock"></i>
            Change Password</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employer', array('action'=>'jobs', 'id' => $company->userid))); ?>">
            <i class="glyphicon glyphicon-list"></i>
            Manage Jobs</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('logout')); ?>" >
            <i class="glyphicon glyphicon-log-out"></i>
            Logout </a>
        </li>
    </ul>
</div>
        <!-- END MENU -->
</div>