<?php 

?>
<div class="profile-sidebar">
<!-- SIDEBAR USERPIC -->
<div class="profile-userpic">
    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
</div>
<!-- END SIDEBAR USERPIC -->
<!-- SIDEBAR USER TITLE -->
<div class="profile-usertitle">
    <div class="profile-usertitle-name">
        <?php echo $company->companyname; ?>
    </div>
    <div class="profile-usertitle-job">
        <?php echo $company->industrytype; ?>
    </div>
</div>
<!-- END SIDEBAR USER TITLE -->
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
    <ul class="nav">
        <li class="active">
            <a href="#">
            <i class="glyphicon glyphicon-home"></i>
            Overview </a>
        </li>
        <li>
            <a href="#">
            <i class="glyphicon glyphicon-picture"></i>
            Change Logo</a>
        </li>
        <li>
            <a href="#">
            <i class="glyphicon glyphicon-user"></i>
            My Account</a>
        </li>
        <li>
            <a href="#">
            <i class="glyphicon glyphicon-lock"></i>
            Change Password</a>
        </li>
        <li>
            <a href="#" target="_blank">
            <i class="glyphicon glyphicon-list"></i>
            Manage Jobs</a>
        </li>
        <li>
            <a href="#">
            <i class="glyphicon glyphicon-log-out"></i>
            Logout </a>
        </li>
    </ul>
</div>
        <!-- END MENU -->
</div>