<?php 
    use Zend\Session\Container;
    
    // Store data in session
    $employee = new Container('user');
?>
<div class="profile-sidebar">
<!-- SIDEBAR USERPIC -->
<div class="profile-userpic">
    <img src="<?php echo $this->serverUrl($employee->picture); ?>" class="img-responsive" alt="" />
</div>
<!-- END SIDEBAR USERPIC -->
<!-- SIDEBAR USER TITLE -->
<div class="profile-usertitle">
    <div class="profile-usertitle-name">
        <?php echo $employee->name; ?>
    </div>
    <div class="profile-usertitle-job">
        Employee Id : <?php echo $employee->username; ?>
    </div>
</div>
<!-- END SIDEBAR USER TITLE -->
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
    <ul class="nav">
        <li class="active">
            <a href="<?php echo $this->serverUrl($this->url('employee')); ?>">
            <i class="glyphicon glyphicon-home"></i>
            Overview </a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'changelogo', 'id' => $employee->id))); ?>">
            <i class="glyphicon glyphicon-picture"></i>
            Change Picture</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'changepass', 'id' => $employee->id))); ?>">
            <i class="glyphicon glyphicon-lock"></i>
            Change Password</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'edit', 'id' => $employee->id))); ?>">
            <i class="glyphicon glyphicon-user"></i>
            Address Information</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'payslips', 'id' => $employee->id))); ?>">
            <i class="glyphicon glyphicon-list"></i>
            My Pay Slip</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'investmentdeclare', 'id' => $employee->id))); ?>">
            <i class="glyphicon glyphicon-list"></i>
            Investment Declaration</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('employee', array('action'=>'grievance', 'id' => $employee->id))); ?>">
            <i class="fa fa-ticket"></i>
            Grievance Zone</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('associate', array('action'=>'logout'))); ?>" >
            <i class="glyphicon glyphicon-log-out"></i>
            Logout </a>
        </li>
    </ul>
</div>
        <!-- END MENU -->
</div>