<?php 
    use Zend\Session\Container;
    
    // Store data in session
    $company = new Container('associate');
?>
<div class="profile-sidebar">
<!-- SIDEBAR USERPIC -->
<div class="profile-userpic">
    <img src="<?php // echo $this->serverUrl($company->logo); ?>" class="img-responsive" alt="" />
</div>
<!-- END SIDEBAR USERPIC -->
<!-- SIDEBAR USER TITLE -->
<div class="profile-usertitle">
    <div class="profile-usertitle-name">
        <?php echo $company->company; ?>
    </div>
    <div class="profile-usertitle-job">
        Employer Id : <?php echo $company->username; ?>
    </div>
</div>
<!-- END SIDEBAR USER TITLE -->
<!-- SIDEBAR MENU -->
<div class="profile-usermenu">
    <ul class="nav">
        <li class="active">
            <a href="<?php echo $this->serverUrl($this->url('company')); ?>">
            <i class="glyphicon glyphicon-home"></i>
            Overview </a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('company', array('action'=>'changelogo', 'id' => $company->id))); ?>">
            <i class="glyphicon glyphicon-picture"></i>
            Change Logo</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('company', array('action'=>'changepass', 'id' => $company->id))); ?>">
            <i class="glyphicon glyphicon-lock"></i>
            Change Password</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('company', array('action'=>'edit', 'id' => $company->id))); ?>">
            <i class="glyphicon glyphicon-user"></i>
            Address Information</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('company', array('action'=>'employee', 'id' => $company->userid))); ?>">
            <i class="glyphicon glyphicon-list"></i>
            Manage Employee</a>
        </li>
        <li>
            <a href="<?php echo $this->serverUrl($this->url('associate', array('action'=>'logout'))); ?>" >
            <i class="glyphicon glyphicon-log-out"></i>
            Logout </a>
        </li>
    </ul>
</div>
        <!-- END MENU -->
</div>