
<?php
$title = 'Contact Us Management';
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
        <tr style="background-color:#2a6496;color: #ffffff">
            <th style="width:10%;">Id</th>
            <th style="width:15%;">Name</th>
            <th style="width:15%;">Email</th>
            <th style="width:15%;">Phone</th>
            <th style="width:40%;">Message</th>
            <th style="width:20%;">Created At</th>
            <th style="width:10%;">&nbsp;</th>
        </tr>
        <?php foreach ($contacts as $val) : ?>
            <tr style="background-color: <?php echo $this->cycle(array('#FFF', '#F0F0F0'))->next(); ?>">
                <td><?php echo $this->escapeHtml($val->id);?></td>
                <td><?php echo $this->escapeHtml($val->name);?></td>
                <td><?php echo $this->escapeHtml($val->email);?></td>
                <td><?php echo $this->escapeHtml($val->phone);?></td>
                <td><?php echo $this->escapeHtml($val->message);?></td>
                <td><?php echo $this->escapeHtml($this->dateFormat(new DateTime($val->createdat), IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM));?></td>
                <td>
                    <a href="<?php echo $this->serverUrl($this->url('admin-contact',
                        array('action'=>'delete', 'id' => $val->id)));?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
