<div class="row">
    <div id="loginbox" class="mainbox col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Login to Account</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px">
                    <a href="<?php echo $this->serverUrl($this->url('forgetpass')); ?>">Forgot password?</a>
                </div>
            </div>
            <div style="padding-top:30px" class="panel-body">
                
                <p>Have an account with us, please log in.</p>
                
                <form id="loginform" class="form-horizontal" role="form"
                      action="<?php echo $this->serverUrl($this->url('associate', array('action' => 'authenticate'))); ?>" method="post">

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="username" value=""
                               placeholder="username or email">
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password"
                               placeholder="password">
                    </div>

                    <div class="input-group">
                        <div class="checkbox">
                            <label>
                                <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                            </label>
                        </div>
                    </div>


                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                            <button id="btn-login" type="submit" class="btn btn-info">
								<i class="icon-hand-right"></i>Login
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>