<div class="row">
    <?php
    if ($this->messages) {
        echo '<ul>';
        foreach ($this->messages as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</ul>';
    }
    ?>
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-lg-12">
        <div id="signupbox" class="mainbox col-lg-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title">Register an Associate</div>
                </div>
                <div class="panel-body">
                    <form id="signupform" class="form-horizontal" role="form"
                          action="<?php echo $this->serverUrl($this->url('associate', array('action' => 'create'))); ?>" method="post">
                        <input type="hidden" name="type" value="employer" />
                        <div class="form-group">
                            <label for="conf-password" class="col-md-3 control-label">Company Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="company" placeholder="Company Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="firstname" class="col-md-3 control-label">Contact First Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="firstname" placeholder="Contact First Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="lastname" class="col-md-3 control-label">Contact Last Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="lastname" placeholder="Contact Last Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-3 control-label">Email</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="email" placeholder="Email Address">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password" class="col-md-3 control-label">Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="conf-password" class="col-md-3 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="conf-password" placeholder="Confirm Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">&nbsp;</label>
                            <div class="col-md-6 checkbox">
                                <input id="login-remember" type="checkbox" name="remember" value="1"> I agree to <a href="javascript:void(0);" target="_blank">Terms & Conditions</a>
                            </div>
                        </div>
                        <?php // echo $captcha->getService()->getHtml(); ?>

                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i>
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function getregion(obj){
	jQuery.ajax({
		url: '/ajax/region',
		type: 'POST',
		dataType: 'JSON',
		data: {'country': jQuery('#country').val()},
		success: function(data, status){
                    $('#statedrop').find('option').remove().end().append('<option value="">---- Select state ----</option>').val(' ');
                    if(data.status == 'error'){
                        // Perform any operation on error
                        $('#statetext').css("display","block");
                        $('#statedrop').css("display","none");
                        $('#statetext').val("");
                        
                    }else{
                        $('#statetext').css("display","none");
                        $('#statedrop').css("display","block");
                        // Perform any operation on success);
                        var region = JSON.parse(JSON.stringify(data.region));
                        for(i = 0; i < data.region.length; i++){
                            $('#statedrop').append($('<option>', { 
                                value: region[i].code,
                                text : region[i].title 
                            }));
                        }
                    }
		},
		error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connect.\n Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('There was some error. Try again.');
                    }
		},
		complete: function(){
                    // Perform any operation need on success/error
		}
	});
    }

</script>