<?php
$title = 'New Country';
$this->headTitle($title);
?>
<div class="row">
    <h3>Creating new page</h3>
    <form class="form-horizontal" role="form" id="tab" method="post" action="<?php echo $this->serverUrl($this->url('admin-country', array('action'=>'save'))); ?>">
        <div class="form-group">
            <label for="title" class="col-md-2 control-label">ISO</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $menu->title; ?>" name="title" placeholder="Title">
            </div>
        </div>
		<div class="form-group">
            <label for="name" class="col-md-2 control-label">Name</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $country->name; ?>" name="name" placeholder="Name">
            </div>
        </div>
		<div class="form-group">
            <label for="nicename" class="col-md-2 control-label">Nicename</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $country->nicename; ?>" name="route" placeholder="Nicename">
            </div>
        </div>
		<div class="form-group">
            <label for="iso3" class="col-md-2 control-label">ISO3</label>
            <div class="col-md-5">
                <input type="text" class="form-control" value="<?php echo $country->iso3; ?>" name="route" placeholder="iso3">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button id="btn-signup" type="submit" class="btn btn-primary"><i class="icon-hand-right"></i>
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>